[package]
name = "gitlab-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
simple-logging.workspace = true
simple_logger.workspace = true
tokio.workspace = true
anyhow.workspace = true
openssl.workspace = true
gitlab-parser = { version = "0.1.0", path = "./gitlab-parser" }

[workspace.dependencies]
log = "0.4.21"
lsp-server = "0.7.6"
lsp-types = "0.95.1"
serde_json = "1.0.114"
simple-logging = "2.0.2"
simple_logger = "4.3.3"
tokio = "1.36.0"
anyhow = "1.0.81"
serde = "1.0.197"
openssl = { version = "0.10", features = ["vendored"] }

[workspace]
members = ["gitlab-parser"]
