# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  publish-crate:
    name: Publish binaries on crate.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo build
